name: Rust

on:
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup path
      if: matrix.os == 'windows-latest'
      run: setx /m PATH "C:\msys64\mingw64\bin;$env:Path"
    - name: Run
      run: |
        echo $PATH
        cargo run
      shell: bash
