name: Rust

on:
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Run on windows
      shell: cmd
      run: |
        set PATH=C:\msys64\mingw64\bin;%PATH%
        cargo run -v
      if: matrix.os == 'windows-latest'
    - name: Run
      run: cargo run -v
      if: matrix.os != 'windows-latest'
